### ISSUE TITLE
Review #1 - Algunos elementos se salen de su contenedor.

### ISSUE THREAD

**Issue by FacundoEG** [AgustinIovane/desafio3#1]
Hola Agustin! estuve revisando tu page y note algunas cositas que me gustaría señalarte.

Primero que todo, noto que el form de la seccion-dos se sale de su propio contenedor:

![image](https://user-images.githubusercontent.com/79592789/134620030-eb740852-e81d-41e0-ac6d-78ccb8985a21.png)

Me gustaría sugerirte que tengas cuidado al usar position:absolute ya que te fija el elemento en la pantalla sobreponiendose a los demas que esten. Por ende es difícil controlarlo. Podrías usar las diferentes opciones de display:flex, ya que el contenedor padre tiene esa propiedad. Ya que es un poco mas escalable no darle espacios tan fijos a los elementos.

Después en modo mobile, me parece que la foto principal de del div presentación se corre hacia la izquierda, además en esa resolución no toma los atributos que le das al parecer.  Podría verse de usar una media query para cada resolución.

Te pediría que revises esas cosas ya que es una premisa del desafío que los elementos estén bien dispuestos en el contenedor.

Cualquier duda avísame y te doy una mano en lo que necesites si?

Espero esos cambios! Saludos!

**Comment by AgustinIovane** [comment]
Hola Facundo, lo del form me extraño porque como podrás ver en la imagen
que te adjunte a mi se me veía bien en cualquier tamaño de pantalla que
hiciera, aun asi le saque el position absolute y utilice más comandos del
flex para que quede bien, y no puse ninguna medida fija, como un top en
pixeles o position absolute en ningún lado, por otra parte logre centrar la
foto principal que acompaña al "bienvenidos a mi site" y ahora si tiene el
desplazamiento cuando voy agrandando la pantalla, también compare con otro
compañero del curso como se veía mi página en su pantalla y no hubo
problemas al parecer. En fin, ahí ya reenvie el desafío con los puntos que
me marcaste, espero que este bien.

Desde ya muchas gracias por la ayuda

Saludos!

**Comment by FacundoEG** [comment]
Hola Agustin! no logre ver ninguna imagen que me hayas adjuntado, la subiste por acá en el issue?

Ahí revise la page y quedo mucho mejor el form! lo había probado en dos navegadores usando también resolución responsive y me sucedía eso. 

Lo de la imagen principal que acompaña a "bienvenidos a mi site" aun se me sigue viendo hacia la izquierda. 

![image](https://user-images.githubusercontent.com/79592789/134774844-4219de51-509c-4be9-8f35-a851f399f133.png)

Quizás no se actualizo bien el commit, de todas formas es algo mínimo. Te lo comento a modo de observación solamente.

Buenísimo por esos cambios entonces! te cierro el issue porque ya se resolvió el tema de los contenedores que se rompían.

Saludos!

**Comment by AgustinIovane** [comment]
Hola Facu, la imagen está adjunta en el email, te conteste por ahí,
mostraba que al menos a mi no se me rompía el form, igual no importa, era
para mostrar como me aparecía a mi . Y en cuanto a la imagen principal me
extraña porque lo puse un un contenedor junto con el título de bienvenidos
a mi site  y use un flex direccion colum, con eso me funciono, pero bueno
se ve que no se actualizo el comit como dijiste vos. Así que nada, gracias
por la disposición.

Nos vemos, saludos!

**Comment by AgustinIovane** [comment]
a por las dudas te aviso, no pude pushear los cambios al repo que mande primero, así que hice un repo nuevo copie todo y ese fue el que reenvié ayer para la corrección de los errores. Por ahí por eso no viste el cambio en la foto, porque lo ves del repo que entregue la primera vez que no se actualizo correctamente.
Saludos!

**Comment by FacundoEG** [comment]
Aaaa eso explica porque no aparecían los cambios! Igual justamente con flex-direction column era la forma que se me ocurría a mi para solucionarlo.

Si lo mandaste de nuevo con los cambios seguro ya pasa! De por sí la page quedo muy buena. 

En el próximo módulo se ve bien el tema de position: absolute y como usarlo de forma escalable. 

Te mando un saludo y espero que la review te haya servido!  

Abrazo

**Comment by AgustinIovane** [comment]
Dale buenísimo, si la verdad me sirvió para hacer los ajustes que faltaban,
muchas gracias! Saludos
